### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by jdnascim** [MKLab-ITI/mmdemo-dockerized#2]
It only collects tweets in English, Spanish, Greek, Turkish, Italian and Catalan. How can I configure the system in order to get tweets in other languages?

**Comment by manosetro** [comment]
This happens due to the the activation of an environmental classifier in the stream-manager-service. This classifier tries to detect whether the collected items are related to environmental and discards the rest. As it's trained on English, Spanish, Greek, Turkish, Italian and Catalan corpora, discards items in other languages. 

To deactivate it change the [config file](https://github.com/MKLab-ITI/mmdemo-dockerized/blob/master/stream-manager-service/conf/streams.conf.xml) of stream manager service. There is an XML section named \<Filters\>, which contains a subsection EnvironmentalClassifier. Please comment it out and rebuild the image of the service.

**Comment by jdnascim** [comment]
It solved my problem. Thank you!
